project:
  type: website

website:
  title: "EpiCentre"
  back-to-top-navigation: true
  page-footer:
    center: 
      - text: "© Camden Health & Wellbeing 2024"
  favicon: camden-logo-white.png
  navbar:
    background: "#29344C"
    foreground: white
    logo: camden-logo-white.png
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: reports.qmd
        text: Reports
      - href: support.qmd
        text: Support
      - about.qmd

format:
  html:
    theme: united
    css: styles/styles.css
    mainfont: Arial
    linkcolor: "#29344c"
    fontcolor: "#4A4949"

editor: visual

freeze: auto
