project:
  type: website

website:
  title: "EpiCentre"
  back-to-top-navigation: true
  page-footer:
    center: 
      - text: "© Camden 2024"
  favicon: camden-logo-white.png
  navbar:
    background: black
    foreground: white
    logo: camden-logo-white.png
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Data
      - href: reports.qmd
        text: Reports
      - href: support.qmd
        text: Support
      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

